name: Build Kernel with Config

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (e.g., ax)'
        required: true
        default: 'ax'

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout linux repository
        uses: actions/checkout@v4
        with:
          repository: amaindex/linux
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libelf-dev libssl-dev \
            gcc-aarch64-linux-gnu

      - name: Configure kernel
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            make defconfig
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          fi

      - name: Enable debug, KVM, and ftrace features
        run: |
          # Enable kernel debugging features
          sed -i 's/# CONFIG_DEBUG_KERNEL is not set/CONFIG_DEBUG_KERNEL=y/' .config
          sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=y/' .config
          sed -i 's/# CONFIG_GDB_SCRIPTS is not set/CONFIG_GDB_SCRIPTS=y/' .config
          
          # Enable KVM and virtualization features
          sed -i 's/# CONFIG_VIRTUALIZATION is not set/CONFIG_VIRTUALIZATION=y/' .config
          sed -i 's/# CONFIG_KVM is not set/CONFIG_KVM=y/' .config
          
          # Enable ftrace features
          sed -i 's/# CONFIG_FTRACE is not set/CONFIG_FTRACE=y/' .config
          sed -i 's/# CONFIG_FUNCTION_TRACER is not set/CONFIG_FUNCTION_TRACER=y/' .config
          sed -i 's/# CONFIG_FUNCTION_GRAPH_TRACER is not set/CONFIG_FUNCTION_GRAPH_TRACER=y/' .config
          sed -i 's/# CONFIG_DYNAMIC_FTRACE is not set/CONFIG_DYNAMIC_FTRACE=y/' .config
          sed -i 's/# CONFIG_FTRACE_MCOUNT_RECORD is not set/CONFIG_FTRACE_MCOUNT_RECORD=y/' .config
          
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            sed -i 's/# CONFIG_KVM_INTEL is not set/CONFIG_KVM_INTEL=y/' .config
            sed -i 's/# CONFIG_KVM_AMD is not set/CONFIG_KVM_AMD=y/' .config
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            sed -i 's/# CONFIG_KVM_ARM_HOST is not set/CONFIG_KVM_ARM_HOST=y/' .config
          fi
          
          # Update the configuration
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            make olddefconfig
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
          fi

      - name: Build kernel
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            make -j$(nproc)
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          fi

      - name: Package kernel
        run: |
          mkdir -p kernel-package
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            cp arch/x86/boot/bzImage kernel-package/
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            cp arch/arm64/boot/Image kernel-package/
          fi
          cp System.map kernel-package/System.map-${{ matrix.arch }}
          cp .config kernel-package/config-${{ matrix.arch }}
          tar -czvf linux-kernel-${{ matrix.arch }}.tar.gz -C kernel-package .

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-${{ matrix.arch }}
          path: linux-kernel-${{ matrix.arch }}.tar.gz 
          retention-days: 90