name: Build Kernel for PVE/QEMU VM (Use Docker Kconfig Logic)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (e.g., ax)'
        required: true
        default: 'ax'
      build_number:
        description: 'Optional build number suffix (e.g., 147)'
        required: false
        default: ''

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64] # Assuming x86_64 build

    steps:
      - name: Checkout linux repository
        uses: actions/checkout@v4
        with:
          repository: amaindex/linux
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libelf-dev libssl-dev \
                                  gcc make libncurses-dev kmod cpio dwarves pahole rsync \
                                  git

      - name: Configure Kernel using Fragments
        run: |
          echo "--- Creating Configuration Fragments ---"

          # --- Base Server Fragment ---
          # (保持不变 - networking core, block, virtio etc. are covered below too, but keep base minimal)
          cat <<EOF > base_server.config
          # Core Boot Requirements
          CONFIG_MODULES=y
          CONFIG_BLK_DEV_SD=y             # Basic SCSI disk
          CONFIG_SCSI=y
          CONFIG_VIRTIO_PCI=y             # Virtio PCI device support
          CONFIG_VIRTIO_BLK=y             # Virtio Block device
          CONFIG_EXT4_FS=y                # Base EXT4 support
          CONFIG_VFAT_FS=y                # EFI partition / boot
          CONFIG_NLS=y
          CONFIG_PARTITION_ADVANCED=y
          CONFIG_EFI_PARTITION=y
          CONFIG_MSDOS_PARTITION=y
          CONFIG_BLK_DEV_INITRD=y
          CONFIG_DEVTMPFS=y
          CONFIG_DEVTMPFS_MOUNT=y
          CONFIG_HW_RANDOM_VIRTIO=y       # Virtio RNG
          CONFIG_TMPFS=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_TMPFS_XATTR=y
          EOF

          # --- Docker Essentials Fragment (Based on provided Kconfig selects) ---
          # This aims to replicate the effect of selecting CONFIG_DOCKER=y and its default sub-options
          cat <<EOF > docker_essentials.config
          # Options selected by CONFIG_DOCKER itself
          CONFIG_PROC_PID_CPUSET=y
          CONFIG_NET=y
          CONFIG_NETDEVICES=y
          CONFIG_NET_CORE=y
          CONFIG_INET=y
          CONFIG_IPV6=y
          CONFIG_NET_L3_MASTER_DEV=y      # For master device features (bonding, bridge, vlan)
          CONFIG_NETFILTER=y
          CONFIG_NETFILTER_ADVANCED=y
          CONFIG_NF_CONNTRACK=y
          CONFIG_NETFILTER_XTABLES=y
          # CONFIG_NF_CONNMARK_IPV4=y # Often selected automatically by others
          CONFIG_IP_NF_IPTABLES=y         # Enable legacy iptables support
          CONFIG_NF_NAT_MASQUERADE_IPV4=y # Potentially superseded by IP_NF_TARGET_MASQUERADE? Let's include both for safety based on Kconfig.
          CONFIG_IP_NF_NAT=y              # Enable legacy iptables NAT
          # CONFIG_IP_NF_TARGET_NETMAP=y # Marked as TODO: required? in Kconfig, skip for now unless needed
          CONFIG_IP_NF_TARGET_REDIRECT=y  # Often needed by Docker proxy
          CONFIG_NET_SCHED=y
          CONFIG_CGROUP_NET_PRIO=y
          CONFIG_CGROUP_NET_CLASSID=y
          # CONFIG_MD=y # RAID/MD, needed? Let's assume base_server covers if needed, or enable later
          CONFIG_TTY=y
          CONFIG_UNIX98_PTYS=y            # Pseudo-terminals
          # CONFIG_HUGETLBFS=y # Marked as TODO: overlay? Let's rely on OVERLAY_FS selection below
          CONFIG_PERSISTENT_KEYRINGS=y
          CONFIG_ENCRYPTED_KEYS=y
          # CONFIG_KEY_DH_OPERATIONS=y # Skip unless needed

          # Options selected via "From ebuild" section in Kconfig (under CONFIG_DOCKER)
          CONFIG_NAMESPACES=y
          CONFIG_NET_NS=y
          CONFIG_PID_NS=y
          CONFIG_IPC_NS=y
          CONFIG_UTS_NS=y
          CONFIG_CGROUPS=y
          CONFIG_CGROUP_CPUACCT=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_FREEZER=y
          CONFIG_CGROUP_SCHED=y
          CONFIG_CPUSETS=y
          CONFIG_MEMCG=y
          CONFIG_KEYS=y
          CONFIG_VETH=m                   # Virtual Ethernet Pair (usually module)
          CONFIG_BRIDGE=y
          CONFIG_BRIDGE_NETFILTER=y
          CONFIG_NF_NAT_IPV4=y            # Core NAT support for IPv4 (nftables backend)
          CONFIG_IP_NF_FILTER=y           # Legacy iptables filter table
          CONFIG_IP_NF_TARGET_MASQUERADE=y # Legacy iptables MASQUERADE target
          CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y # Match address type
          CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y # Match conntrack state
          CONFIG_NF_NAT=y                 # Core NAT framework
          CONFIG_NF_NAT_NEEDED=y          # Auto-selects NAT helpers when needed
          CONFIG_POSIX_MQUEUE=y
          CONFIG_USER_NS=y
          CONFIG_SECCOMP=y
          CONFIG_CGROUP_PIDS=y
          # CONFIG_BLK_DEV_THROTTLING=y # Usually selected by BLK_CGROUP if needed
          # CONFIG_CFQ_GROUP_IOSCHED=y # CFQ is often replaced by BFQ or none nowadays
          CONFIG_CGROUP_HUGETLB=y
          CONFIG_NET_CLS_CGROUP=y
          CONFIG_FAIR_GROUP_SCHED=y       # CFS group scheduling
          CONFIG_RT_GROUP_SCHED=y         # Realtime group scheduling
          CONFIG_IP_VS=m                  # IP Virtual Server (module)
          CONFIG_IP_VS_PROTO_TCP=m
          CONFIG_IP_VS_PROTO_UDP=m
          CONFIG_IP_VS_NFCT=m             # IPVS Connection Tracking
          CONFIG_VXLAN=m                  # Virtual Extensible LAN (module)
          CONFIG_IPVLAN=m                 # IP VLAN (module)
          CONFIG_MACVLAN=m                # MAC VLAN (module)
          CONFIG_DUMMY=m                  # Dummy network interface (module)
          CONFIG_DEVPTS_MULTIPLE_INSTANCES=y # Support multiple PTY instances
          CONFIG_MEMCG_KMEM=y             # Account kernel memory to memcg

          # Options selected by DOCKER_STATISTICS (default y)
          CONFIG_RESOURCE_COUNTERS=y
          CONFIG_BLK_CGROUP=y             # Block layer cgroup support
          CONFIG_IOSCHED_CFQ=y            # CFQ IO scheduler (needed for older cgroup v1 IO control)
          CONFIG_CGROUP_PERF=y
          CONFIG_CFS_BANDWIDTH=y          # CPU bandwidth control

          # Options selected by DOCKER_SECURE_NETWORKS (default y)
          CONFIG_XFRM_ALGO=y              # IPsec algorithms
          CONFIG_XFRM_USER=y              # IPsec userspace interface

          # Options selected by DOCKER_DEVICE_MAPPER (default y)
          CONFIG_BLK_DEV_DM=y             # Device Mapper base
          CONFIG_DM_THIN_PROVISIONING=y   # Thin provisioning target
          CONFIG_EXT4_FS=y                # Ensure EXT4 (likely already set)
          CONFIG_EXT4_FS_POSIX_ACL=y
          CONFIG_EXT4_FS_SECURITY=y

          # Options selected by DOCKER_OVERLAY_FS (default y)
          CONFIG_OVERLAY_FS=y             # Overlay Filesystem
          # CONFIG_EXT4_FS_SECURITY=y # Duplicate
          # CONFIG_EXT4_FS_POSIX_ACL=y # Duplicate
          EOF

          # --- Tailscale Support Fragment ---
          # (保持不变)
          cat <<EOF > tailscale.config
          CONFIG_TUN=m                  # TUN device support
          # INET, IPV6, Netfilter/NAT/NFtables covered now by docker_essentials
          # CONFIG_VXLAN=m # Already included in docker_essentials
          EOF

          # --- Debug Fragment ---
          # (保持不变)
          cat <<EOF > debug.config
          CONFIG_DEBUG_KERNEL=y
          CONFIG_DEBUG_INFO=y
          CONFIG_DEBUG_INFO_DWARF5=y
          CONFIG_GDB_SCRIPTS=y
          CONFIG_FTRACE=y
          CONFIG_FUNCTION_TRACER=y
          CONFIG_FUNCTION_GRAPH_TRACER=y
          CONFIG_KPROBES=y
          CONFIG_KGDB=y
          CONFIG_MAGIC_SYSRQ=y
          CONFIG_IKCONFIG=y
          CONFIG_IKCONFIG_PROC=y
          EOF

          # --- Disable Unnecessary Fragment ---
          # (保持不变)
          cat <<EOF > disable.config
          # CONFIG_DRM is not set
          # CONFIG_SND is not set
          # CONFIG_SOUND is not set
          # CONFIG_USB_COMMON is not set
          # CONFIG_HID is not set
          # CONFIG_CFG80211 is not set
          # CONFIG_TIGON3 is not set
          # CONFIG_E100 is not set
          # CONFIG_E1000E is not set
          # CONFIG_R8169 is not set
          # CONFIG_BNX2 is not set
          EOF

          echo "--- Starting Base Configuration (defconfig) ---"
          make defconfig

          echo "--- Merging Custom Configuration Fragments ---"
          # Use the new docker_essentials fragment
          ./scripts/kconfig/merge_config.sh -m .config \
              base_server.config \
              docker_essentials.config \
              tailscale.config \
              debug.config \
              disable.config

          # *** 调试步骤 1: 检查 合并后、第一个 olddefconfig 之前 的配置 (更新grep) ***
          echo "--- Config AFTER merge, BEFORE olddefconfig ---"
          echo "Checking critical Docker network options:"
          # Check key options from the new fragment, including both legacy and nft NAT parts selected
          grep -E '^CONFIG_BRIDGE=|^# CONFIG_BRIDGE |^CONFIG_BRIDGE_NETFILTER=|^# CONFIG_BRIDGE_NETFILTER |^CONFIG_OVERLAY_FS=|^# CONFIG_OVERLAY_FS |^CONFIG_VETH=|^# CONFIG_VETH |^CONFIG_IP_NF_TARGET_MASQUERADE=|^# CONFIG_IP_NF_TARGET_MASQUERADE |^CONFIG_NF_NAT_IPV4=|^# CONFIG_NF_NAT_IPV4 |^CONFIG_NF_NAT_NEEDED=|^# CONFIG_NF_NAT_NEEDED |^CONFIG_NF_NAT_MASQUERADE_IPV4=|^# CONFIG_NF_NAT_MASQUERADE_IPV4 ' .config || echo "关键Docker网络配置状态未找到或状态未知"
          echo "---------------------------------------------"

          echo "--- Applying Merged Configuration (olddefconfig) ---"
          make olddefconfig

          # *** 调试步骤 2: 检查 第一个 olddefconfig 之后 的配置 (更新grep) ***
          echo "--- Config AFTER first olddefconfig ---"
          echo "Checking critical Docker network options:"
          grep -E '^CONFIG_BRIDGE=|^# CONFIG_BRIDGE |^CONFIG_BRIDGE_NETFILTER=|^# CONFIG_BRIDGE_NETFILTER |^CONFIG_OVERLAY_FS=|^# CONFIG_OVERLAY_FS |^CONFIG_VETH=|^# CONFIG_VETH |^CONFIG_IP_NF_TARGET_MASQUERADE=|^# CONFIG_IP_NF_TARGET_MASQUERADE |^CONFIG_NF_NAT_IPV4=|^# CONFIG_NF_NAT_IPV4 |^CONFIG_NF_NAT_NEEDED=|^# CONFIG_NF_NAT_NEEDED |^CONFIG_NF_NAT_MASQUERADE_IPV4=|^# CONFIG_NF_NAT_MASQUERADE_IPV4 ' .config || echo "关键Docker网络配置状态未找到或状态未知"
          echo "---------------------------------------"

          echo "--- Setting Kernel Version Suffix (CONFIG_LOCALVERSION) ---"
          LOCAL_VERSION_SUFFIX=""
          if [ -n "${{ github.event.inputs.build_number }}" ]; then
            LOCAL_VERSION_SUFFIX="-${{ github.event.inputs.build_number }}"
          fi
          LOCAL_VERSION_SUFFIX="${LOCAL_VERSION_SUFFIX}-${{ matrix.arch }}"
          LOCAL_VERSION_SUFFIX=$(echo "${LOCAL_VERSION_SUFFIX}" | head -c 64)
          echo "Setting CONFIG_LOCALVERSION=${LOCAL_VERSION_SUFFIX}"
          sed -i "s/CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=\"${LOCAL_VERSION_SUFFIX}\"/" .config

          echo "--- Finalizing Configuration with Local Version (olddefconfig) ---"
          make olddefconfig

          # *** 调试步骤 3: 检查 最终 olddefconfig 之后 的配置 (更新grep) ***
          echo "--- Config AFTER final olddefconfig ---"
          echo "Checking critical Docker network options:"
          grep -E '^CONFIG_BRIDGE=|^# CONFIG_BRIDGE |^CONFIG_BRIDGE_NETFILTER=|^# CONFIG_BRIDGE_NETFILTER |^CONFIG_OVERLAY_FS=|^# CONFIG_OVERLAY_FS |^CONFIG_VETH=|^# CONFIG_VETH |^CONFIG_IP_NF_TARGET_MASQUERADE=|^# CONFIG_IP_NF_TARGET_MASQUERADE |^CONFIG_NF_NAT_IPV4=|^# CONFIG_NF_NAT_IPV4 |^CONFIG_NF_NAT_NEEDED=|^# CONFIG_NF_NAT_NEEDED |^CONFIG_NF_NAT_MASQUERADE_IPV4=|^# CONFIG_NF_NAT_MASQUERADE_IPV4 ' .config || echo "关键Docker网络配置状态未找到或状态未知"
          echo "-------------------------------------"


          echo "--- Configuration Complete ---"

      # Build Kernel and Modules step remains the same
      - name: Build Kernel and Modules
        run: |
          make -j$(nproc) bzImage
          make -j$(nproc) modules

      # Prepare Kernel Package step remains the same
      - name: Prepare Kernel Package for Manual Install
        run: |
          echo "--- Determining Full Kernel Version ---"
          KERNEL_SUFFIX=$(make -s kernelrelease)
          echo "Full Kernel Version Suffix: ${KERNEL_SUFFIX}"
          echo "KERNEL_SUFFIX=${KERNEL_SUFFIX}" >> $GITHUB_ENV

          INSTALL_PATH=$(pwd)/_install
          mkdir -p ${INSTALL_PATH}/boot
          mkdir -p ${INSTALL_PATH}/lib/modules

          echo "--- Copying Kernel Files ---"
          cp arch/x86/boot/bzImage ${INSTALL_PATH}/boot/vmlinuz-${KERNEL_SUFFIX}
          cp System.map ${INSTALL_PATH}/boot/System.map-${KERNEL_SUFFIX}
          cp .config ${INSTALL_PATH}/boot/config-${KERNEL_SUFFIX}

          echo "--- Installing Modules ---"
          make modules_install INSTALL_MOD_PATH=${INSTALL_PATH}

          echo "--- Verifying Module Directory Existence ---"
          if [ ! -d "${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}" ]; then
            echo "ERROR: Module directory ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX} was not created!"
            ls -l ${INSTALL_PATH}/lib/modules/
            exit 1
          fi
          echo "Module directory found: ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}"

          rm -f ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}/build
          rm -f ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}/source

          echo "--- Kernel Package Contents (Staging) ---"
          ls -lR ${INSTALL_PATH}/

          echo "--- Creating Tarball ---"
          tar -czvf linux-kernel-package-${KERNEL_SUFFIX}.tar.gz -C ${INSTALL_PATH} .

      # Upload Artifact step remains the same
      - name: Upload Kernel Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-package-${{ env.KERNEL_SUFFIX }}
          path: linux-kernel-package-${{ env.KERNEL_SUFFIX }}.tar.gz
          retention-days: 90