name: Build Kernel for PVE/QEMU VM (Fragment Based - Docker Fixes)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (e.g., ax)'
        required: true
        default: 'ax'
      build_number:
        description: 'Optional build number suffix (e.g., 147)'
        required: false
        default: ''

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64] # Assuming x86_64 build

    steps:
      - name: Checkout linux repository
        uses: actions/checkout@v4
        with:
          repository: amaindex/linux
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libelf-dev libssl-dev \
                                  gcc make libncurses-dev kmod cpio dwarves pahole rsync \
                                  git

      - name: Configure Kernel using Fragments
        run: |
          echo "--- Creating Configuration Fragments ---"

          # --- Base Server Fragment ---
          # (Keep the previous base_server.config content here)
          cat <<EOF > base_server.config
          # Core Boot Requirements (Built-in where critical)
          CONFIG_MODULES=y
          CONFIG_BLOCK=y
          CONFIG_BLK_DEV_SD=y
          CONFIG_SCSI=y
          CONFIG_VIRTIO_PCI=y
          CONFIG_VIRTIO_SCSI=y
          CONFIG_VIRTIO_BLK=y
          CONFIG_EXT4_FS=y
          CONFIG_VFAT_FS=y
          CONFIG_PARTITION_ADVANCED=y
          CONFIG_EFI_PARTITION=y
          CONFIG_MSDOS_PARTITION=y
          CONFIG_BLK_DEV_INITRD=y
          CONFIG_DEVTMPFS=y
          CONFIG_DEVTMPFS_MOUNT=y
          CONFIG_HW_RANDOM_VIRTIO=y

          # Common Server Features (Modules where appropriate)
          CONFIG_VIRTIO_NET=m
          CONFIG_VIRTIO_BALLOON=m
          CONFIG_VIRTIO_CONSOLE=m
          CONFIG_VIRTIO_INPUT=m
          # CONFIG_VIRTIO_GPU=m
          CONFIG_BLK_DEV_LOOP=m
          CONFIG_BLK_DEV_NVME=m
          CONFIG_BLK_DEV_DM=m
          CONFIG_BLK_DEV_MD=m
          CONFIG_BTRFS_FS=m
          CONFIG_XFS_FS=m
          CONFIG_NFS_FS=m
          CONFIG_NFSD=m
          CONFIG_ISO9660_FS=m
          CONFIG_BRIDGE=m                 # Bridge support itself (needed by docker0)
          CONFIG_VLAN_8021Q=m
          CONFIG_AHCI=m
          CONFIG_ATA_PIIX=m
          CONFIG_SCSI_SAS_LIBSAS=m
          CONFIG_ISCSI_TCP=m
          CONFIG_DM_CRYPT=m
          CONFIG_CRYPTO_CBC=y
          CONFIG_CRYPTO_XTS=y
          CONFIG_CRYPTO_AES_X86_64=m
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_TMPFS_XATTR=y
          EOF

          # --- Docker Support Fragment (Revised based on logs) ---
          cat <<EOF > docker.config
          # Filesystems & Core Features
          CONFIG_OVERLAY_FS=y
          CONFIG_NAMESPACES=y
          CONFIG_UTS_NS=y
          CONFIG_IPC_NS=y
          CONFIG_USER_NS=y
          CONFIG_PID_NS=y
          CONFIG_NET_NS=y

          # CGroups
          CONFIG_CGROUPS=y
          CONFIG_CGROUP_CPUACCT=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_FREEZER=y
          CONFIG_CGROUP_NET_PRIO=y
          CONFIG_CGROUP_PERF=y
          CONFIG_CGROUP_SCHED=y
          CONFIG_CPUSETS=y
          CONFIG_MEMCG=y
          CONFIG_CGROUP_PIDS=y
          CONFIG_CGROUP_BPF=y

          # Security
          CONFIG_SECCOMP=y
          CONFIG_SECCOMP_FILTER=y
          CONFIG_SECURITY_APPARMOR=m
          CONFIG_SECURITY_SELINUX=m
          CONFIG_KEYS=y
          CONFIG_EXT4_FS_POSIX_ACL=y
          CONFIG_EXT4_FS_SECURITY=y
          CONFIG_POSIX_MQUEUE=y

          # --- Networking (Crucial Fixes based on logs) ---
          CONFIG_NETFILTER=y              # Core Netfilter
          CONFIG_BRIDGE_NETFILTER=y       # *** FIX: Enable bridge netfilter (br_netfilter), built-in ***
          CONFIG_BRIDGE_VLAN_FILTERING=y  # Often needed for bridge setups

          # Core NAT Framework (Required by both iptables/nftables)
          CONFIG_NF_NAT=y                 # *** FIX: Ensure core NAT is built-in ***

          # iptables Backend Support (Legacy + Compatibility)
          CONFIG_NETFILTER_XTABLES=y      # Core xtables support
          CONFIG_IP_NF_IPTABLES=y         # Enable iptables support
          CONFIG_IP_NF_FILTER=y           # iptables FILTER table
          CONFIG_IP_NF_NAT=y              # iptables NAT table support
          CONFIG_IP_NF_MANGLE=y           # iptables MANGLE table support
          CONFIG_IP_NF_RAW=m              # iptables RAW table (module OK)
          CONFIG_IP_NF_TARGET_MASQUERADE=y # *** FIX: Ensure legacy MASQUERADE target is built-in ***
          CONFIG_IP_NF_TARGET_REDIRECT=m  # REDIRECT target (module OK)
          # IPv6 iptables support (Enable if needed)
          CONFIG_IP6_NF_IPTABLES=y
          CONFIG_IP6_NF_FILTER=m
          CONFIG_IP6_NF_MANGLE=m
          CONFIG_IP6_NF_RAW=m
          CONFIG_IP6_NF_NAT=m
          CONFIG_IP6_NF_TARGET_MASQUERADE=m

          # nf_tables Backend Support (Needed for modern iptables/nft)
          CONFIG_NF_TABLES=y              # *** FIX: Ensure NF_TABLES is built-in ***
          CONFIG_NF_TABLES_IPV4=y         # NFtables for IPv4
          CONFIG_NF_TABLES_IPV6=y         # NFtables for IPv6
          CONFIG_NFT_CT=y                 # NFtables conntrack support
          CONFIG_NFT_CHAIN_NAT=y          # *** FIX: Allow NAT chains in nftables, built-in ***
          CONFIG_NF_NAT_IPV4=y            # NFtables IPv4 NAT support
          CONFIG_NF_NAT_IPV6=y            # NFtables IPv6 NAT support
          CONFIG_NFT_MASQ=y               # *** FIX: NFtables MASQUERADE target, built-in ***
          CONFIG_NFT_MASQ_IPV4=y          # *** FIX: NFtables MASQUERADE for IPv4, built-in ***
          CONFIG_NFT_MASQ_IPV6=y          # *** FIX: NFtables MASQUERADE for IPv6, built-in ***
          CONFIG_NFT_FIB_INET=y           # NFtables routing integration

          # Netfilter Conntrack (Dependency for NAT)
          CONFIG_NF_CONNTRACK=y           # *** FIX: Ensure connection tracking is built-in ***
          CONFIG_NF_CONNTRACK_IPV4=y
          CONFIG_NF_CONNTRACK_IPV6=y

          # Netfilter Matches & Helpers
          CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=m
          CONFIG_NETFILTER_XT_MATCH_CONNTRACK=m # Needed by Docker rules
          CONFIG_NETFILTER_XT_MATCH_IPVS=m
          CONFIG_NETFILTER_XT_MARK=m
          CONFIG_NF_NAT_FTP=m
          CONFIG_NF_CONNTRACK_FTP=m
          CONFIG_NF_NAT_TFTP=m
          CONFIG_NF_CONNTRACK_TFTP=m

          # Networking (Virtual Devices)
          CONFIG_VETH=m                   # Essential for container pairs
          CONFIG_IPVLAN=m
          CONFIG_MACVLAN=m
          CONFIG_DUMMY=m

          # IPVS (Optional, for Kubernetes)
          CONFIG_IP_VS=m
          CONFIG_IP_VS_NFCT=y
          CONFIG_IP_VS_PROTO_TCP=y
          CONFIG_IP_VS_PROTO_UDP=y
          CONFIG_IP_VS_RR=m
          EOF

          # --- Tailscale Support Fragment ---
          # Many options overlap with Docker and are now set to '=y' there.
          # This fragment now mainly ensures TUN and specific extras if needed.
          cat <<EOF > tailscale.config
          CONFIG_TUN=m                  # TUN device support
          CONFIG_INET=y                 # Already enabled
          CONFIG_IPV6=y                 # Already enabled

          # Core Netfilter/NAT/NFtables already covered and set to =y in docker.config

          # IPTables legacy (Also covered in docker.config)
          # CONFIG_IP_TABLES=y # Old name, NF_IPTABLES is preferred
          # CONFIG_IP6_TABLES=y

          # Other Networking Features
          CONFIG_VXLAN=m                # Useful for some overlay networks
          EOF

          # --- Debug Fragment ---
          # (Keep the previous debug.config content here)
          cat <<EOF > debug.config
          CONFIG_DEBUG_KERNEL=y
          CONFIG_DEBUG_INFO=y
          CONFIG_DEBUG_INFO_DWARF5=y
          CONFIG_GDB_SCRIPTS=y
          CONFIG_FTRACE=y
          CONFIG_FUNCTION_TRACER=y
          CONFIG_FUNCTION_GRAPH_TRACER=y
          CONFIG_KPROBES=y
          CONFIG_KGDB=y
          CONFIG_MAGIC_SYSRQ=y
          EOF

          # --- Disable Unnecessary Fragment ---
          # (Keep the previous disable.config content here)
          cat <<EOF > disable.config
          # CONFIG_DRM is not set
          # CONFIG_SND is not set
          # CONFIG_SOUND is not set
          # CONFIG_USB_COMMON is not set
          # CONFIG_HID is not set
          # CONFIG_CFG80211 is not set
          # CONFIG_TIGON3 is not set
          # CONFIG_E100 is not set
          # CONFIG_E1000E is not set
          # CONFIG_R8169 is not set
          # CONFIG_BNX2 is not set
          EOF

          echo "--- Starting Base Configuration (defconfig) ---"
          make defconfig

          echo "--- Merging Custom Configuration Fragments ---"
          # Merge order ensures docker specific needs might override base if needed
          ./scripts/kconfig/merge_config.sh -m .config \
              base_server.config \
              docker.config \
              tailscale.config \
              debug.config \
              disable.config

          echo "--- Applying Merged Configuration (olddefconfig) ---"
          make olddefconfig

          echo "--- Setting Kernel Version Suffix (CONFIG_LOCALVERSION) ---"
          LOCAL_VERSION_SUFFIX=""
          if [ -n "${{ github.event.inputs.build_number }}" ]; then
            LOCAL_VERSION_SUFFIX="-${{ github.event.inputs.build_number }}"
          fi
          LOCAL_VERSION_SUFFIX="${LOCAL_VERSION_SUFFIX}-${{ matrix.arch }}"
          LOCAL_VERSION_SUFFIX=$(echo "${LOCAL_VERSION_SUFFIX}" | head -c 64)
          echo "Setting CONFIG_LOCALVERSION=${LOCAL_VERSION_SUFFIX}"
          sed -i "s/CONFIG_LOCALVERSION=.*/CONFIG_LOCALVERSION=\"${LOCAL_VERSION_SUFFIX}\"/" .config

          echo "--- Finalizing Configuration with Local Version (olddefconfig) ---"
          make olddefconfig

          echo "--- Configuration Complete ---"

      # Build Kernel and Modules step remains the same
      - name: Build Kernel and Modules
        run: |
          make -j$(nproc) bzImage
          make -j$(nproc) modules

      # Prepare Kernel Package step remains the same
      - name: Prepare Kernel Package for Manual Install
        run: |
          echo "--- Determining Full Kernel Version ---"
          KERNEL_SUFFIX=$(make -s kernelrelease)
          echo "Full Kernel Version Suffix: ${KERNEL_SUFFIX}"
          echo "KERNEL_SUFFIX=${KERNEL_SUFFIX}" >> $GITHUB_ENV

          INSTALL_PATH=$(pwd)/_install
          mkdir -p ${INSTALL_PATH}/boot
          mkdir -p ${INSTALL_PATH}/lib/modules

          echo "--- Copying Kernel Files ---"
          cp arch/x86/boot/bzImage ${INSTALL_PATH}/boot/vmlinuz-${KERNEL_SUFFIX}
          cp System.map ${INSTALL_PATH}/boot/System.map-${KERNEL_SUFFIX}
          cp .config ${INSTALL_PATH}/boot/config-${KERNEL_SUFFIX}

          echo "--- Installing Modules ---"
          make modules_install INSTALL_MOD_PATH=${INSTALL_PATH}

          echo "--- Verifying Module Directory Existence ---"
          if [ ! -d "${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}" ]; then
            echo "ERROR: Module directory ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX} was not created!"
            ls -l ${INSTALL_PATH}/lib/modules/
            exit 1
          fi
          echo "Module directory found: ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}"

          rm -f ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}/build
          rm -f ${INSTALL_PATH}/lib/modules/${KERNEL_SUFFIX}/source

          echo "--- Kernel Package Contents (Staging) ---"
          ls -lR ${INSTALL_PATH}/

          echo "--- Creating Tarball ---"
          tar -czvf linux-kernel-package-${KERNEL_SUFFIX}.tar.gz -C ${INSTALL_PATH} .

      # Upload Artifact step remains the same
      - name: Upload Kernel Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-package-${{ env.KERNEL_SUFFIX }}
          path: linux-kernel-package-${{ env.KERNEL_SUFFIX }}.tar.gz
          retention-days: 90